source'https://github.com/CocoaPods/Specs.git'
platform:ios, '9.0'

inhibit_all_warnings!

target 'OneSecond' do
    pod 'SCRecorder'
    pod 'FMDB',          '~> 2.5'
    pod 'MBProgressHUD', '~> 0.9.1'
end
